import React from 'react';
import InfoPageLayout, { PageH2, PageP, PageLink, PageUl, PageLi } from '../components/InfoPageLayout';
import { CONTACT_EMAIL, POLICY_DATE } from '../constants';

export default function TermsPage() {
  return (
    <InfoPageLayout title="Terms of Use">
      <PageP>Last updated: {POLICY_DATE}</PageP>
      <PageP>By using DocSim Checker, you agree to the following terms.</PageP>

      <PageH2>What this tool is</PageH2>
      <PageP>
        DocSim Checker provides an automated similarity comparison between two documents you provide. It is a general-purpose text comparison tool, not a certified plagiarism detection or academic integrity service.
      </PageP>

      <PageH2>No guarantee of accuracy</PageH2>
      <PageP>
        Similarity scores are generated algorithmically and may not perfectly reflect meaning, intent, or context. Results should be used as a starting point for your own judgment, not as definitive proof of originality, plagiarism, or copying. We make no guarantees about the accuracy or completeness of results.
      </PageP>

      <PageH2>Acceptable use</PageH2>
      <PageP>You agree not to:</PageP>
      <PageUl>
        <PageLi>Use this tool for any unlawful purpose</PageLi>
        <PageLi>Attempt to abuse, overload, or circumvent rate limits through automated means</PageLi>
        <PageLi>Upload content you do not have the right to process (e.g., content under legal restriction from being copied or analyzed)</PageLi>
      </PageUl>

      <PageH2>No liability</PageH2>
      <PageP>
        DocSim Checker is provided &quot;as is,&quot; without warranties of any kind. We are not liable for any decisions made based on results generated by this tool, including academic, legal, or professional consequences.
      </PageP>

      <PageH2>Changes to the service</PageH2>
      <PageP>
        We may modify, suspend, or discontinue any part of the service at any time, including free usage limits, without prior notice.
      </PageP>

      <PageH2>Contact</PageH2>
      <PageP>
        Questions about these terms? <PageLink href={`mailto:${CONTACT_EMAIL}`}>Contact us</PageLink>.
      </PageP>
    </InfoPageLayout>
  );
}
